[project]
name = "nyc-taxi-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=6.2.2",
    "dbt-core>=1.8",
    "dbt-duckdb>=1.8",
    "duckdb>=1.0",
    "pandas>=3.0.3",
    "requests>=2.34.2",
    "streamlit>=1.36",
]
