name: nyc_taxi
version: "1.0.0"
profile: nyc_taxi

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  nyc_taxi:
    staging:
      +materialized: incremental
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
